# Generated by Django 4.0 on 2022-03-01 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('temperature_min', models.FloatField()),
                ('temperature_max', models.FloatField()),
                ('temperature_ave', models.FloatField()),
                ('temperature_threshold_highest', models.FloatField()),
                ('temperature_threshold_high', models.FloatField()),
                ('temperature_threshold_low', models.FloatField()),
                ('temperature_threshold_lowest', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm', models.DateTimeField()),
                ('temperature', models.FloatField(null=True)),
                ('humidity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('temperature_ave', models.FloatField(null=True)),
                ('humidity_ave', models.IntegerField(null=True)),
                ('humidity_min', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='humidity_min', to='app.timedata')),
                ('temperature_max', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temperature_max', to='app.timedata')),
                ('temperature_min', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temperature_min', to='app.timedata')),
            ],
        ),
    ]
