# Generated by Django 4.0 on 2022-03-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedata',
            name='battery',
            field=models.IntegerField(null=True),
        ),
    ]
