# Generated by Django 4.0 on 2022-03-07 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_timedata_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydata',
            name='humidity_ave',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daydata',
            name='humidity_min',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='humidity_min', to='app.timedata'),
        ),
        migrations.AlterField(
            model_name='daydata',
            name='temperature_ave',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daydata',
            name='temperature_max',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temperature_max', to='app.timedata'),
        ),
        migrations.AlterField(
            model_name='daydata',
            name='temperature_min',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temperature_min', to='app.timedata'),
        ),
        migrations.AlterField(
            model_name='daydata',
            name='weather',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timedata',
            name='battery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timedata',
            name='humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timedata',
            name='is_external',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timedata',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
