# Generated by Django 3.2.12 on 2022-03-11 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220310_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daydata',
            old_name='humidity_ave',
            new_name='humidity_avg',
        ),
        migrations.RenameField(
            model_name='daydata',
            old_name='temperature_ave',
            new_name='temperature_avg',
        ),
        migrations.RenameField(
            model_name='normaldata',
            old_name='temperature_ave',
            new_name='temperature_avg',
        ),
        migrations.RenameField(
            model_name='normaldata',
            old_name='temperature_threshold_high',
            new_name='temperature_avg_high',
        ),
        migrations.RenameField(
            model_name='normaldata',
            old_name='temperature_threshold_highest',
            new_name='temperature_avg_highest',
        ),
        migrations.RenameField(
            model_name='normaldata',
            old_name='temperature_threshold_low',
            new_name='temperature_avg_low',
        ),
        migrations.RenameField(
            model_name='normaldata',
            old_name='temperature_threshold_lowest',
            new_name='temperature_avg_lowest',
        ),
        migrations.AddField(
            model_name='normaldata',
            name='temperature_max_high',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normaldata',
            name='temperature_max_highest',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normaldata',
            name='temperature_max_low',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normaldata',
            name='temperature_max_lowest',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normaldata',
            name='temperature_min_high',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normaldata',
            name='temperature_min_highest',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normaldata',
            name='temperature_min_low',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normaldata',
            name='temperature_min_lowest',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normaldata',
            name='year_end',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normaldata',
            name='year_start',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
