# Generated by Django 3.2.12 on 2022-03-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_daydata_is_incomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydata',
            name='is_incomplete',
            field=models.BooleanField(default=True),
        ),
    ]
