# Generated by Django 3.2.12 on 2022-03-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_daydata_is_incomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydata',
            name='weather',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
