# Generated by Django 3.2.12 on 2022-03-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_daydata_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydata',
            name='weather',
            field=models.CharField(default='', max_length=50),
        ),
    ]
