# Generated by Django 4.0.6 on 2022-08-12 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormalData',
            fields=[
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('day', models.DateField(primary_key=True, serialize=False)),
                ('temperature_min', models.FloatField()),
                ('temperature_max', models.FloatField()),
                ('temperature_avg', models.FloatField()),
                ('temperature_min_lowest', models.FloatField()),
                ('temperature_min_low', models.FloatField()),
                ('temperature_min_high', models.FloatField()),
                ('temperature_min_highest', models.FloatField()),
                ('temperature_max_lowest', models.FloatField()),
                ('temperature_max_low', models.FloatField()),
                ('temperature_max_high', models.FloatField()),
                ('temperature_max_highest', models.FloatField()),
                ('temperature_avg_lowest', models.FloatField()),
                ('temperature_avg_low', models.FloatField()),
                ('temperature_avg_high', models.FloatField()),
                ('temperature_avg_highest', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeData',
            fields=[
                ('tm', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('is_external', models.BooleanField(blank=True, null=True)),
                ('battery', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayData',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
                ('temperature_avg', models.FloatField(blank=True, null=True)),
                ('humidity_avg', models.FloatField(blank=True, null=True)),
                ('weather', models.CharField(default='', max_length=50)),
                ('is_incomplete', models.BooleanField(default=True)),
                ('humidity_max', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='humidity_max', to='viewer.timedata')),
                ('humidity_min', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='humidity_min', to='viewer.timedata')),
                ('temperature_max', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temperature_max', to='viewer.timedata')),
                ('temperature_min', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temperature_min', to='viewer.timedata')),
            ],
        ),
    ]
